### PR TITLE
Define AbstractQuantity

### PR DESCRIPTION
**Pull request by giordano**
Start addressing #186 by defining an `AbstractQuantity` type.  <s>I've marked this PR as work-in-progress because I'm not sure I've used the new abstract type wherever it's needed, at least tests pass locally.</s>

### CODE REVIEW

**Comment by giordano** [comment]
I've played with this branch in `PhysicalConstants.jl` and it seems to be sufficient for my current needs: https://github.com/JuliaPhysics/PhysicalConstants.jl/issues/2#issuecomment-457912121

The only thing I would recommend doing is to define an API function (`value`?) to access the value of an `AbstractQuantity`, which for the concrete type `Quantity` could be `value(x::Quantity) = x.val`.  In my tests for `PhysicalConstants.jl` I've implemented `Base.getproperty(c::Constant, sym::Symbol)`

**Comment by c42f** [comment]
> The only thing I would recommend doing is to define an API function to access the value of an AbstractQuantity.

Just wondering - is this just `ustrip`, or does it mean something different?

**Comment by giordano** [comment]
Ustrip is defined as
```julia
@inline ustrip(x::Quantity) = ustrip(x.val)
```
So strictly speaking it doesn't simply access to the val field. However, I'm having difficulties to find a case where the results would be different

**Comment by c42f** [comment]
Yes I haven't read enough of the internals to know why it's recursive, but it seems like it might have the meaning you want.

**Comment by giordano** [comment]
Yeah, anyway I'm not too concerned about that, for me it's sufficient this PR is merged

**Comment by ajkeller34** [comment]
I'm late on the explanation but `ustrip` is recursive because of types like `Quantity{<:Level}`, i.e. `(20u"dBm/Hz").val == 20u"dBm"`, but presumably you want `ustrip(20u"dBm/Hz") == 20`. There is some special sauce needed to make logarithmic quantities work right.

**Pull request merged**
